POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name":"arfin11",
    "email":"arfin11@mail.com",
    "password":"123456",
    "identity_type": "KTP",
    "identity_number": "1234567890",
    "address": "Jalan Sudirman No. 123"
}


###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/1

###
POST http://localhost:3000/api/v1/users/auth/register
Content-Type: application/json

{
    "name":"arfin10",
    "email":"arfin10@mail.com",
    "password":"123456",
    "password_confirmation": "123456"
}

###
POST http://localhost:3000/api/v1/users/auth/login
Content-Type: application/json

{
    "email":"arfin7@mail.com",
    "password":"123456"
}

###
GET http://localhost:3000/api/v1/users/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjk3NzM4MjI5fQ.bv9p1L6Jk1-HLHZXmbtkJMf1FLTVh5QB_OAd2s77DFw

###
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "user_id": 2,
    "bank_name": "BRI",
    "bank_account_number": "0123456789",
    "balance": 1000000
}


###
GET http://localhost:3000/api/v1/accounts

###
GET http://localhost:3000/api/v1/accounts/1

###
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "source_account_id": 1, 
    "destination_account_id": 2,
    "amount": 100000
}


###
GET http://localhost:3000/api/v1/transactions

###
GET http://localhost:3000/api/v1/transactions/1