POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name":"arfin2",
    "email":"arfin@mail.com",
    "password":"123456",
    "identity_type": "KTP",
    "identity_number": "1234567890",
    "address": "Jalan Sudirman No. 123"
}


###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/35

###
POST http://localhost:3000/api/v1/users/auth/register
Content-Type: application/json

{
    "name":"arfin",
    "email":"arfin@mail.com",
    "password":"123456",
    "password_confirmation": "123456"
}

###
POST http://localhost:3000/api/v1/users/auth/login
Content-Type: application/json

{
    "email":"arfin@mail.com",
    "password":"123456"
}

###
GET http://localhost:3000/api/v1/users/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTUxLCJpYXQiOjE2OTc5MzcxNjZ9.5xaLgjPMc5RzV-jgz2oXaUgWXUqRUNtVCYvwD4TAk-E

###
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "user_id": 1326,
    "bank_name": "BRI",
    "bank_account_number": "0123456789",
    "balance": 1000000
}


###
GET http://localhost:3000/api/v1/accounts

###
GET http://localhost:3000/api/v1/accounts/44

###
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "source_account_id": 66, 
    "destination_account_id": 67,
    "amount": 100000
}


###
GET http://localhost:3000/api/v1/transactions

###
GET http://localhost:3000/api/v1/transactions/54